version: '3'
services:
  app:
    image: node:18.14
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 8080:80
  db:
    image: mysql:8.0
    ports:
      - 13306:3306
    environment:
      TZ: "Asia/Tokyo"
    env_file: ./.env
    volumes:
      - db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
volumes:
  node_modules:
  db_data:
